# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d34762bd3575053d73396b7d3c58b62099e36106eb7b3d55d43a24a17382277ecf032ceb94cb4871896e52b7c67670fa98708c89ed014b95733f08346e910b3

test:
  secret_key_base: 4b149dabc58a599e4e4406c05b48e3398bfbd48f34db6b12e4c4de7c285807f468af10fe135ec2a7db2c56a3c9ab49befeb2884f60aaa63df8851cfb2c79e341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
